version: 0.2

phases:
  install:
    commands:
      echo $CODEBUILD_SOURCE_VERSION;
      PRID=$(echo $CODEBUILD_SOURCE_VERSION | sed "s/pr/pull/g");
      echo "Checking out $PRID";
      git fetch origin $PRID/head:pr_test;
      git checkout pr_test;
      echo "Installing MXNet";
      apt-get update;
      pip install --upgrade pip;
      pip install mxnet-mkl;
      echo "Installing Tensorflow";
      pip install tensorflow;
      echo "Installing Theano";
      pip install theano;
      pip install pillow;
      pip install graphviz;
      pip install pydot;
      echo "Installing Keras from source";
      pip install -e .[visualize,tests];
      pip uninstall --yes keras;

  build:
    commands:
      echo "Running Keras Unit Tests and Integration Tests for all the backends";
      py.test tests/ --ignore=tests/keras/utils/;
      py.test tests/keras/utils/;
      echo "Running PEP tests";
      py.test --pep8 -m pep8 -n0;